### ISSUE TITLE
__del__ method throws "Resource Already Closed" error

### ISSUE THREAD

**Issue by WJohnsonNEU** [AnnaGiasson/PythonEquipmentDrivers#20]
The __del__ method in some classes throws "Resource already closed" error when trying to set_local. Observed in Source "Keithley_2231A" and Multimeter "HP_34401A" classes, though the issue may be present in other classes with __del__ methods that include set_local or other resource commands.

I fixed the issue on my local fork by commenting out the set_local command in each __del__ function, but additional review of __del__ calls may be warranted (seems a general __del__ or end of program method is closing the resource before the resource's specific __del__ is called).

**Comment by cmgriffin** [comment]
Thanks for creating this issue. I think wrapping the `__del__`  contents in a try/except is probably the way to fix this so that it suppresses the error. However, having `__del__` implemented where it may or may not being doing anything might cause confusion or create tricky/inconsistent code. [Python also does not guarantee](https://docs.python.org/3/reference/datamodel.html#object.__del__) that `__del__` is called when the interpreter exits so maybe these cleanup actions are best handled at the application level i.e. in the test script. 

Generally `object.__del__()` can also be called explicitly in a script by using the statement `del object`

I'll add this change to some other changes I've been working on unless you want to submit your own pull request

**Comment by WJohnsonNEU** [comment]
Hi Chris,

Sounds good, and if you are already working on the project feel free to
resolve the issue as part of your push. I'm going to focus on why my Iout
meters arent getting readings today.

Thanks,
Will
